#!/usr/bin/env python3
import sys

from logging import debug, info
from dataclasses import replace

from utils import setup_logging, get_elf_mem_from_path, pplog, get_str

from elf import *
from signatures import read_signatures_from_file

assert len(sys.argv) >= 4, "./converter <plik ET_REL> <plik z listą funkcji> <docelowy plik ET_REL>"

setup_logging()

mem = get_elf_mem_from_path(sys.argv[1])

elf = RelElf(context_elf_mem=mem)

elf = elf.with_switched_bitness()

elf.change_relas_to_rels()

signatures = read_signatures_from_file(sys.argv[2])

elf.add_thunks(signatures)

for s in elf.sections:
    if s.header.found_name == b'.note.gnu.property':    
        s.content = bytes()
        s.header.sh_size = 0

debug("Final elf:")
pplog(debug, elf.ehdr)
pplog(debug, elf.sections)

elf.write_to_file(sys.argv[3])
